module StagingTable
  class BulkInserter
    attr_reader model: singleton(ActiveRecord::Base)
    attr_reader batch_size: Integer

    def initialize: (singleton(ActiveRecord::Base) model, ?batch_size: Integer) -> void

    # Insert records in batches
    def insert: (Array[Hash[String | Symbol, untyped]] records) -> void

    private

    TIMESTAMP_COLUMNS: Array[String]

    def apply_timestamps: (Array[Hash[String | Symbol, untyped]] records) -> Array[Hash[String | Symbol, untyped]]
    def record_has_key?: (Hash[String | Symbol, untyped] record, String key) -> bool
    def connection: () -> ActiveRecord::ConnectionAdapters::AbstractAdapter
    def quote: (untyped value) -> String
  end
end
